// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccreoxhtgtyzcorrfzqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcmVveGh0Z3R5emNvcnJmenF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM5NTgsImV4cCI6MjA2MDEzOTk1OH0.rxSQXAsCuAkfcCTIVQ8hGORQm6_n3kiLrP2iVzsYsQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);